// Code generated by protoc-gen-go. DO NOT EDIT.
// source: status.proto

/*
Package status is a generated protocol buffer package.

It is generated from these files:
	status.proto

It has these top-level messages:
	Empty
*/
package status

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterType((*Empty)(nil), "status.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TestError service

type TestErrorClient interface {
	GetError(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type testErrorClient struct {
	cc *grpc.ClientConn
}

func NewTestErrorClient(cc *grpc.ClientConn) TestErrorClient {
	return &testErrorClient{cc}
}

func (c *testErrorClient) GetError(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/status.TestError/GetError", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TestError service

type TestErrorServer interface {
	GetError(context.Context, *Empty) (*Empty, error)
}

func RegisterTestErrorServer(s *grpc.Server, srv TestErrorServer) {
	s.RegisterService(&_TestError_serviceDesc, srv)
}

func _TestError_GetError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestErrorServer).GetError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/status.TestError/GetError",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestErrorServer).GetError(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _TestError_serviceDesc = grpc.ServiceDesc{
	ServiceName: "status.TestError",
	HandlerType: (*TestErrorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetError",
			Handler:    _TestError_GetError_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "status.proto",
}

func init() { proto.RegisterFile("status.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 88 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x2e, 0x49, 0x2c,
	0x29, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0xd8, 0xb9, 0x58,
	0x5d, 0x73, 0x0b, 0x4a, 0x2a, 0x8d, 0xcc, 0xb9, 0x38, 0x43, 0x52, 0x8b, 0x4b, 0x5c, 0x8b, 0x8a,
	0xf2, 0x8b, 0x84, 0xb4, 0xb8, 0x38, 0xdc, 0x53, 0xa1, 0x6c, 0x5e, 0x3d, 0xa8, 0x46, 0xb0, 0x3a,
	0x29, 0x54, 0xae, 0x12, 0x43, 0x12, 0x1b, 0xd8, 0x40, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xeb, 0x0b, 0xc8, 0x6b, 0x60, 0x00, 0x00, 0x00,
}
